# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#F7F7F7'

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = ['#F7F7F7', '#F7F7F7', '#F7F7F7']

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#242424'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#242424'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#F7F7F7'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#242424'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#5D5D5D'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#242424'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#5D5D5D'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#242424'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#F7F7F7'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#242424'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#F7F7F7'

# List of domains that should always be loaded, despite being ad-
# blocked. Domains may contain * and ? wildcards and are otherwise
# required to exactly match the requested domain. Local domains are
# always exempt from hostblocking.
# Type: List of String
c.content.host_blocking.whitelist = []

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal, "Helvetica Neue"'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt "Helvetica Neue"'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt "Helvetica Neue"'

# Font family for standard fonts.
# Type: FontFamily
c.fonts.web.family.standard = None

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 0, 'left': 5, 'right': 5, 'top': 0}

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'about:blank'

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://www.google.com/search?hl=en&q={}', 'ddg': 'https://duckduckgo.com/?q={}', 'google': 'https://www.google.com/search?hl=en&q={}', 'wa': 'https://wiki.archlinux.org/?search={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://google.com'

# Format to use for the window title. The same placeholders like for
# `tabs.title.format` are defined.
# Type: FormatString
c.window.title_format = '{perc}{title}'
