" Should be placed in / linked to ~/.vimrc
"""
" PLUGINS
"""
call plug#begin("~/.vim/plugged")
    Plug 'sjl/badwolf'
    Plug 'itchyny/lightline.vim'
    Plug '844196/lightline-badwolf.vim'
    Plug 'itchyny/vim-gitbranch'
call plug#end()

let g:lightline = { 'colorscheme': 'badwolf' }

"""
" VIM CONFIGURATION
"""
" Pull common vim configuration
source ~/.vim.common

" Show status bar
set laststatus=2

" hlsearch trailing
set hlsearch

" color
syntax on
colorscheme badwolf

" trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
