# General Unix config files

# Prompt
export PATH=$PATH:$HOME/.local/bin

if [ -f $HOME/.local/lib/python3.8/site-packages/powerline/bindings/bash/powerline.sh ]; then
    $HOME/.local/bin/powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    source $HOME/.local/lib/python3.8/site-packages/powerline/bindings/bash/powerline.sh
fi

# CLI colors
export CLICOLORS=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export TERM=xterm-256color

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
# alias
alias ls='ls -Gph'
alias ll='ls -l'
alias la='ll -a'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if type nvim &> /dev/null; then
    alias vim='nvim'
fi

# If git-completion exist, then load it.
if [ -f ~/.bash/git-completion.bash ]; then
    source ~/.bash/git-completion.bash
fi
